language: android

android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.1
  - android-25

jdk:
- oraclejdk8

before_install:
- nvm install 6

install:
- npm install -g cordova ionic
- npm install
- ionic info

script:
- npm run ionic:build
- ionic state restore
- cordova build android
