matrix:
  include:
  - os: linux
    language: android
    android:
      components:
      - tools
      - platform-tools
      - tools
      - extra
      - build-tools-27.0.1
      - android-27
    env: TARGET_PLATFORM=android
  - os: osx
    language: objective-c
    osx_image: xcode8.3
    env: TARGET_PLATFORM=ios

before_install:
- nvm install 8

install:
- npm install -g cordova
- npm install

script:
- npm run build --prod
- cordova platform add "$TARGET_PLATFORM"
- cordova build "$TARGET_PLATFORM"
