matrix:
  include:
  - language: android
    android:
      components:
      - tools
      - platform-tools
      - tools
      - extra
      - build-tools-28.0.3
      - android-28
    env:
      - TARGET_FRAMEWORK=cordova
      - TARGET_PLATFORM=android
  - language: objective-c
    osx_image: xcode9.4
    env:
      - TARGET_FRAMEWORK=cordova
      - TARGET_PLATFORM=ios
  - language: node_js
    env:
      - EXTRA_ARGS="-- --base-href=/openlap/ --service-worker"

before_install:
- nvm install 10

install:
- npm install -g cordova ionic
- npm install

script:
- ionic $TARGET_FRAMEWORK build $TARGET_PLATFORM --prod $EXTRA_ARGS
